import os
import time
import random
from dotenv import load_dotenv
from langchain_chroma import Chroma
from langchain_google_genai import ChatGoogleGenerativeAI, GoogleGenerativeAIEmbeddings
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from google.api_core.exceptions import ResourceExhausted, ServiceUnavailable

# --- CONFIGURATION ---
load_dotenv() 

# Folders
COMPANY_KNOWLEDGE_BASE = "company_knowledge_base"
GRI_STANDARDS_FOLDER = "gri_extracted_data"
OUTPUT_REPORT_FILE = "FINAL_GRI_REPORT.md"

# Verify Key
if not os.getenv("GOOGLE_API_KEY"):
    raise ValueError("GOOGLE_API_KEY not found in .env. Please add it.")

# 1. SETUP RETRIEVER (Using Google Embeddings)
def get_retriever():
    print("Loading Knowledge Base with Google Embeddings...")
    embedding_function = GoogleGenerativeAIEmbeddings(model="models/embedding-001")
    
    vectorstore = Chroma(
        persist_directory=COMPANY_KNOWLEDGE_BASE, 
        embedding_function=embedding_function
    )
    
    return vectorstore.as_retriever(search_kwargs={"k": 5})

# 2. CHECK IF SECTION ALREADY EXISTS (Resumability)
def is_already_processed(title):
    if not os.path.exists(OUTPUT_REPORT_FILE):
        return False
    
    with open(OUTPUT_REPORT_FILE, "r", encoding="utf-8") as f:
        content = f.read()
    
    # Check if the header exists
    return f"## {title}" in content

# 3. ROBUST GENERATION FUNCTION (Handles Rate Limits)
def generate_section_safe(chain, inputs, max_retries=5):
    attempt = 0
    while attempt < max_retries:
        try:
            return chain.invoke(inputs)
        except (ResourceExhausted, ServiceUnavailable):
            attempt += 1
            # Exponential Backoff: Wait 20s, 40s, 80s... + random jitter
            wait_time = (20 * attempt) + random.randint(1, 5)
            print(f"    ⚠️ Google Rate Limit hit. Waiting {wait_time} seconds before Retry {attempt}/{max_retries}...")
            time.sleep(wait_time)
        except Exception as e:
            print(f"    ❌ Unexpected Error: {e}")
            return None # Skip this section if it's a non-recoverable error
    
    print("    ❌ Failed after max retries. Moving on.")
    return None

# 4. MAIN EXECUTION
def generate_report():
    if not os.path.exists(GRI_STANDARDS_FOLDER):
        print(f"❌ ERROR: The folder '{GRI_STANDARDS_FOLDER}' does not exist.")
        return

    # Initialize File if not exists
    if not os.path.exists(OUTPUT_REPORT_FILE):
        with open(OUTPUT_REPORT_FILE, "w", encoding="utf-8") as f:
            f.write("# GRI Sustainability Report\nGenerated by Google Gemini Agent\n\n")

    retriever = get_retriever()
    
    # Initialize Google Gemini LLM
    # We use 'gemini-1.5-flash' for speed/cost or 'gemini-pro' for quality.
    llm = ChatGoogleGenerativeAI(
        model="gemini-1.5-flash", 
        temperature=0.3,
        convert_system_message_to_human=True
    )

    template = """
    You are an expert ESG Auditor. Your task is to write a report section based EXACTLY on the GRI Disclosure requirements provided.
    
    --- GRI STANDARD REQUIREMENTS (THE RULES) ---
    {gri_standard}
    
    --- COMPANY DATA EVIDENCE (FROM PDF) ---
    {context}
    
    --- INSTRUCTIONS ---
    1. Answer the specific requirements in the GRI Standard using only the Company Data provided.
    2. If the company data is missing, state clearly: "Data for [Requirement] is not available in the provided documents."
    3. Be professional, concise, and factual.
    4. If you find data, cite the source page number provided in the context.
    
    OUTPUT REPORT SECTION:
    """
    prompt = ChatPromptTemplate.from_template(template)
    chain = prompt | llm | StrOutputParser()

    print(f"\nScanning for files in: {GRI_STANDARDS_FOLDER}")

    for root, dirs, files in os.walk(GRI_STANDARDS_FOLDER):
        for file in files:
            if file.endswith(".txt"):
                file_path = os.path.join(root, file)
                disclosure_title = file.replace(".txt", "").replace("_", " ")
                
                # --- CHECKPOINT: Skip if already done ---
                if is_already_processed(disclosure_title):
                    print(f"--> Skipping (Already Done): {disclosure_title}")
                    continue

                print(f"--> Processing: {disclosure_title}...")
                
                try:
                    # Read Rule
                    with open(file_path, "r", encoding="utf-8") as f:
                        gri_text = f.read()
                        
                    if not gri_text.strip():
                        continue

                    # Retrieve Data (This might also hit rate limits, so we wrap it)
                    docs = []
                    try:
                        docs = retriever.invoke(disclosure_title + " " + gri_text[:200])
                    except Exception as e:
                        print(f"    ⚠️ Retrieval Error (skipping): {e}")
                        continue

                    context_text = "\n\n".join([d.page_content + f"\n(Source Page: {d.metadata.get('page_number')})" for d in docs])

                    # Generate with Safe Retry
                    response = generate_section_safe(chain, {
                        "gri_standard": gri_text,
                        "context": context_text
                    })
                    
                    if response:
                        # --- SAVE IMMEDIATELY (Append Mode) ---
                        with open(OUTPUT_REPORT_FILE, "a", encoding="utf-8") as f:
                            f.write(f"## {disclosure_title}\n\n{response}\n\n---\n\n")
                        
                        print("    ✅ Section saved.")
                        
                        # Mandatory sleep to respect Free Tier Limits (approx 15 requests/min)
                        time.sleep(10) 

                except Exception as e:
                    print(f"    ❌ Critical Error processing file: {e}")

    print(f"\n✅ Processing finished! Report updated at: {OUTPUT_REPORT_FILE}")

if __name__ == "__main__":
    generate_report()